Swal.fire({
	title: 'Estimado Usario',
	text: 'Pago Exitoso',
	icon: 'success',
	confirmButtonText: 'Aceptar',
	footer:'¡Importante!',
	backdrop:true,
	position:'center',
	allowOutsideClick:false,
	allowEscapeKey:false,
	allowEnterKey:false,
	stopKeydownPropagation: false,
	showConfirmButton:true,
	confirmButtonColor: '#2980B9',
	confirmButtonAriaLabel: 'Aceptar',
	buttonsStyling:true,
	showCloseButton: true,
	closeButtonAriaLabel:'cerrarAlerta',
});