Swal.fire({
	title: 'Estimado Usario',
	text: '¿Desea confirmar la reservación?',
	icon: 'qestion',
	confirmButtonText: 'Aceptar',
	footer:'¡Debe confirmar o cerrar la ventana!',
	backdrop:true,
	position:'center',
	allowOutsideClick:false,
	allowEscapeKey:false,
	allowEnterKey:false,
	stopKeydownPropagation: false,
	showConfirmButton:true,
	confirmButtonColor: '#2980B9',
	confirmButtonAriaLabel: 'Aceptar',
	buttonsStyling:true,
	showCloseButton: true,
	closeButtonAriaLabel:'cerrarAlerta',
});
